version: '3'
services:
  jupyterlab:
    build: .
    ports:
      - 8888:8888
    environment: 
      TOKEN: mark
      PASSWORD: demox
    volumes:
      - ./config:/root/.jupyter
      - ./app:/home
    command: "jupyter notebook"